# Auto-generated by /configure for project: claudetesting
# Edit this file to adjust module detection for your codebase.
# Run update_kb.py with --module-config project-claudetesting.py to use it.

PROJECT_NAME = "claudetesting"
PROJECT_ROOT = "/Users/ajaykumarsahu/Documents/TI/Projects/AI/MoshHamedani/claude/claudetesting"

MODULE_PATTERNS = [
    # (module_name, [glob_patterns])
    ("app", ["**/src/*.jsx", "**/src/*.js", "**/src/*.css"]),
    ("assets", ["**/src/assets/**"]),
    ("config", ["**/vite.config.js", "**/eslint.config.js", "**/package.json"]),
    ("public", ["**/public/**"]),
]

INCLUDE_EXTENSIONS = {
    ".jsx",
    ".js",
    ".css",
    ".html",
    ".json",
    ".md",
}

TEST_COMMAND = ""
LINT_COMMAND = "eslint ."
BUILD_COMMAND = "vite build"
TYPE_CHECK_COMMAND = ""
